config/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', admin.site.urls),
]

unit/urls.py
from django.urls import path
from . import views

app_name = 'unit'

urlpatterns = [
    # post views
    path('search/', views.airman_search, name='airman_search'),
    # path('search/', views.airman_first_name_search(), name='airman_first_name_search'),
    path('<int:year>/<int:month>/<int:day>/<slug:airman>/',
         views.airman_detail,
         name='airman_detail'),
    path('naughty/', views.NaughtyListView.as_view(), name='all_naughty_list'),
    path('profiles/', views.ProfileListView.as_view(), name='all_profile_list'),
    path('ptls/', views.PhysicalTrainingLeaderListView.as_view(), name='all_ptl_list'),
    path('ufpms/', views.UnitFitnessProgramManagerListView.as_view(), name='all_ufpm_list'),
    path('', views.AirmanListView.as_view(), name='airman_list'),
]

unit/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse


class ActiveManager(models.Manager):
    def get_queryset(self):
        return super(ActiveManager, self).get_queryset().filter(active_status='active')


class Airman(models.Model):
    ACTIVE_CHOICE = (
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
    )

    RANK_CHOICE = (
        ('E-1/AB', 'E-1/AB'),
        ('E-2/Amn', 'E-2/Amn'),
        ('E-3/A1C', 'E-3/A1C'),
        ('E-4/SrA', 'E-4/SrA'),
        ('E-5/SSgt', 'E-5/SSgt'),
        ('E-6/TSgt', 'E-6/TSgt'),
        ('E-7/MSgt', 'E-7/MSgt'),
        ('E-8/SMSgt', 'E-8/SMSgt'),
        ('E-9/CMSgt', 'E-9/CMSgt'),
        ('O-1/2nd Lt', 'O-1/2nd Lt'),
        ('O-2/1st Lt', 'O-2/1st Lt'),
        ('O-3/Capt', 'O-3/Capt'),
        ('O-4/Maj', 'O-4/Maj'),
        ('O-5/Lt Col', 'O-5/Lt Col'),
        ('O-6/Col', 'O-6/Col'),
        ('O-7/Brig Gen', 'O-7/Brig Gen'),
        ('O-8/Maj Gen', 'O-8/Maj Gen'),
        ('O-9/Lt Gen', 'O-9/Lt Gen'),
        ('O-10/Gen', 'O-10/General'),
    )
    FITNESS_CHOICE = (
        ('Excellent', 'EXCELLENT'),
        ('Satisfactory', 'SATISFACTORY'),
        ('Pass', 'PASS'),
        ('Unsatisfactory', 'UNSATISFACTORY'),
        ('Fail', 'FAIL'),
        ('Exemption', 'EXEMPTION'),
    )
    airman_id = models.AutoField(primary_key=True, serialize=True)
    fitness_level = models.CharField(max_length=50,
                                     choices=FITNESS_CHOICE,
                                     default='satisfactory')
    rank = models.CharField(max_length=15,
                            choices=RANK_CHOICE,
                            default='E-1/AB')
    first_name = models.CharField(max_length=20)
    middle_initial = models.CharField(max_length=5)
    last_name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=14,
                                    null=True)
    ssn = models.CharField(max_length=11)
    airman_slug = models.SlugField(max_length=50,
                                   unique_for_date='test_date')
    test_date = models.DateField()
    ptl = models.BooleanField(default=False)
    ufpm = models.BooleanField(default=False)
    active_status = models.CharField(max_length=10,
                                     choices=ACTIVE_CHOICE,
                                     default='Active')

    class Meta:
        verbose_name = 'Airman'
        verbose_name_plural = 'AIRMEN'
        ordering = ('last_name',)

    def __str__(self):
        return f"{self.rank} {self.first_name} {self.middle_initial} {self.last_name}"

    objects = models.Manager()
    active = ActiveManager()

    def get_absolute_url(self):
        return reverse('unit:airman_detail',
                       args=[self.test_date.year,
                             self.test_date.month,
                             self.test_date.day,
                             self.airman_slug])


class Naughty(models.Model):
    NAUGHTY_CHOICE = (
        ('Fail', 'FAIL'),
        ('Unsatisfactory', 'UNSATISFACTORY'),
        ('Non-Current', 'NON-CURRENT'),
    )
    naughty_id = models.AutoField(primary_key=True, serialize=True)
    airman_id = models.ForeignKey(
        Airman,
        on_delete=models.CASCADE, )
    failure_date = models.DateField()
    be_well_completion_date = models.DateField()
    status_level = models.CharField(max_length=50,
                                    choices=NAUGHTY_CHOICE, )

    class Meta:
        verbose_name = 'Failure, Unsatisfactory, & Non-Current'
        verbose_name_plural = 'FAILURE, UNSATISFACTORY, & NON-CURRENTS'
        ordering = ('-failure_date',)

    def clean(self):
        if self.failure_date and self.be_well_completion_date:
            if self.failure_date > self.be_well_completion_date:
                raise ValidationError('Failure Date cannot be after the Be Well Completion Date')

    def __str__(self):
        return f"{self.airman_id}"


class PhysicalTrainingLeader(models.Model):
    ptl_id = models.AutoField(primary_key=True, serialize=True)
    airman_id = models.ForeignKey(
        Airman,
        on_delete=models.CASCADE, )
    ptl_certification_date = models.DateField()
    ptl_expiration_date = models.DateField()
    cpr_expiration_date = models.DateField()

    class Meta:
        verbose_name = 'Physical Training Leader'
        verbose_name_plural = 'PHYSICAL TRAINING LEADERS'
        ordering = ('ptl_expiration_date',)

    def clean(self):
        if self.ptl_certification_date and self.ptl_expiration_date:
            if self.ptl_certification_date >= self.ptl_expiration_date:
                raise ValidationError('Expiration Date must be later than the Certification Date')

    def __str__(self):
        return f"{self.airman_id}"


class UnitFitnessProgramManager(models.Model):
    ufpm_id = models.AutoField(primary_key=True, serialize=True)
    airman_id = models.ForeignKey(
        Airman,
        on_delete=models.CASCADE, )
    ptl_id = models.ForeignKey(
        PhysicalTrainingLeader,
        on_delete=models.CASCADE, )
    ufpm_certification_date = models.DateField()
    ufpm_expiration_date = models.DateField()

    class Meta:
        verbose_name = 'Unit Fitness Program Manager'
        verbose_name_plural = 'UNIT FITNESS PROGRAM MANAGERS'
        ordering = ('ufpm_expiration_date',)

    def clean(self):
        if self.ufpm_certification_date and self.ufpm_expiration_date:
            if self.ufpm_certification_date >= self.ufpm_expiration_date:
                raise ValidationError('Expiration Date must be later than the Certification Date')
        if self.airman_id and self.ptl_id:
            if str(self.airman_id) != str(self.ptl_id):
                raise ValidationError("Airman ID and PTL ID Must Match")

    def __str__(self):
        return f"{self.airman_id}"


class Profile(models.Model):
    profile_id = models.AutoField(primary_key=True, serialize=True)
    airman_id = models.ForeignKey(
        Airman,
        on_delete=models.CASCADE, )
    profile_start_date = models.DateField()
    profile_expiration_date = models.DateField()
    profile_details = models.TextField()

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'PROFILES'
        ordering = ('profile_expiration_date',)

    def clean(self):
        if self.profile_start_date and self.profile_expiration_date:
            if self.profile_start_date > self.profile_expiration_date:
                raise ValidationError('Profile Start Date must be later than the Profile Expiration Date')

    def __str__(self):
        return f"{self.airman_id}"

unit/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField()

unit/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404
from .models import Airman, Naughty, Profile, PhysicalTrainingLeader, UnitFitnessProgramManager
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from .forms import SearchForm


# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from django.contrib.postgres.search import TrigramSimilarity


def airman_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('first_name', 'last_name', 'ssn', )
            search_query = SearchQuery(query)
            results = Airman.active.annotate(
                search=search_vector,
                ranking=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-ranking')
    return render(request,
                  'unit/airman/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})


# def airman_first_name_search(request):
#     form = SearchForm()
#     query = None
#     results = []
#     if 'query' in request.GET:
#         form = SearchForm(request.GET)
#         if form.is_valid():
#             query = form.cleaned_data['query']
#             results = Airman.active.annotate(
#                 similarity=TrigramSimilarity('first_name', query),
#             ).filter(similarity__gt=0.1).order_by('-similarity')
#     return render(request,
#                   'unit/airman/search.html',
#                   {'form': form,
#                    'query': query,
#                    'results': results})

# def airman_list(request):
#     object_list = Airman.active.all()
#     paginator = Paginator(object_list, 10) # airmen in each page
#     page = request.GET.get('page')
#     try:
#         airmen = paginator.page(page)
#     except PageNotAnInteger:
#         # If page is not an integer deliver the first page
#         airmen = paginator.page(1)
#     except EmptyPage:
#         # If page is out of range deliver last page of results
#         airmen = paginator.page(paginator.num_pages)
#     return render(request,
#                   'unit/airman/list.html',
#                   {'page': page,
#                    'airmen': airmen})

class AirmanListView(ListView):
    queryset = Airman.active.all()
    context_object_name = 'airmen'
    paginate_by = 10
    template_name = 'unit/airman/list.html'


def airman_detail(request, year, month, day, airman):
    airman = get_object_or_404(Airman,
                               airman_slug=airman,
                               active_status='active',
                               test_date__year=year,
                               test_date__month=month,
                               test_date__day=day)
    return render(request,
                  'unit/airman/detail.html',
                  {'airman': airman})


class NaughtyListView(ListView):
    model = Naughty
    template_name = 'unit/naughty/list.html'
    context_object_name = 'all_naughty_list'


class ProfileListView(ListView):
    model = Profile
    template_name = 'unit/profile/list.html'
    context_object_name = 'all_profile_list'


class PhysicalTrainingLeaderListView(ListView):
    model = PhysicalTrainingLeader
    template_name = 'unit/ptl/list.html'
    context_object_name = 'all_ptl_list'


class UnitFitnessProgramManagerListView(ListView):
    model = UnitFitnessProgramManager
    template_name = 'unit/ufpm/list.html'
    context_object_name = 'all_ufpm_list'

unit/templates/unit/airman/detail.html
{% extends "unit/base.html" %}
{% block title %}{{ airman.rank }} {{ airman.first_name }} {{ airman.last_name }}{% endblock %}
{% block content %}
    <h1>{{ airman.rank }} {{ airman.first_name|capfirst }} {{ airman.last_name|capfirst }}</h1>
    <p class="date">
        Rank: {{ airman.rank }}
        <br><br>
        SSN: {{ airman.ssn }}
        <br><br>
        Test Date: {{ airman.test_date }}
        <br><br>
        Fitness Level:
        {% if airman.fitness_level == 'Excellent' %}
            <strong style="color: green;">{{ airman.fitness_level }}</strong>
        {% elif airman.fitness_level == 'Satisfactory' or airman.fitness_level == 'Pass' %}
            <strong style="color: orange;">{{ airman.fitness_level }}</strong>
        {% elif airman.fitness_level == 'Unsatisfactory' or airman.fitness_level == 'Fail' %}
            <strong style="color: red;">{{ airman.fitness_level }}</strong>
        {% else %}
            {{ airman.fitness_level }}
        {% endif %}
        <br><br>
        PTL:
        {% if airman.ptl %}
            Yes
        {% else %}
            No
        {% endif %}
        <br><br>
        UFPM:
        {% if airman.ufpm %}
            Yes
        {% else %}
            No
        {% endif %}
    </p>
{% endblock %}

unit/templates/unit/airman/list.html
{% extends "unit/base.html" %}
{% block title %}All ASTS Airmen{% endblock %}
{% block content %}
    <h1>Airmen</h1>
    {% for airman in airmen %}
        <h2>
            <a href="{{ airman.get_absolute_url }}">
                <strong>{{ airman.rank }} {{ airman.last_name|capfirst }}, {{ airman.first_name|capfirst }}</strong>
            </a>
        </h2>
        <p class="date">
            Fitness Level:
            {% if airman.fitness_level == 'Excellent' %}
                <strong style="color: green;">{{ airman.fitness_level }}</strong>
            {% elif airman.fitness_level == 'Satisfactory' or airman.fitness_level == 'Pass' %}
                <strong style="color: orange;">{{ airman.fitness_level }}</strong>
            {% elif airman.fitness_level == 'Unsatisfactory' or airman.fitness_level == 'Fail' %}
                <strong style="color: red;">{{ airman.fitness_level }}</strong>
            {% else %}
                {{ airman.fitness_level }}
            {% endif %}
        </p>
        <p class="date">
            Test Date: {{ airman.test_date }}
        </p>
    {% endfor %}
    {% include "pagination.html" with page=page_obj %}
{% endblock %}

unit/templates/unit/airman/search.html
{% extends "unit/base.html" %}
{% block title %}Search for Airman{% endblock %}
{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for airman in results %}
            <h4><a href="{{ airman.get_absolute_url }}">{{ airman.rank }} {{ airman.first_name }} {{ airman.last_name }}</a></h4>
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "unit:airman_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for airman</h1>
        <form method="get">
            First Name, Last Name, or SSN
            {{ form.as_p|capfirst }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}